import {mkdirSync, existsSync, writeFileSync} from "fs";
import {join, dirname} from "path";
import {fileURLToPath} from "url";

const capitalizeFirstLetter = (string) => {
  return string.charAt(0).toUpperCase() + string.slice(1);
};

// eslint-disable-next-line id-match
const __filename = fileURLToPath(import.meta.url);

// eslint-disable-next-line id-match
const __dirname = dirname(__filename);

// eslint-disable-next-line no-undef
const layoutName = process.argv[2];

// eslint-disable-next-line no-undef
const layoutPath = process.argv[3] || "library"; // Default path library/layouts if not provided

const layoutsFolder = join(__dirname, "..", "src", `${layoutPath}/layouts`);

// Check if it's a TypeScript project
const isTypeScriptProject = existsSync(join(__dirname, "..", "tsconfig.json"));

// Set appropriate file extensions based on the project type
const fileExtension = isTypeScriptProject ? "ts" : "js";

const componentExtension = isTypeScriptProject ? "tsx" : "jsx";

const indexPath = join(layoutsFolder, `index.${fileExtension}`);

if (!layoutName) {
  console.error("Please provide a layout name");
  console.info("Usage: npm run create:layout <layout-name> <layout-path>");
  // eslint-disable-next-line no-undef
  process.exit(1);
}

// Create the layouts folder if it does not exist
if (!existsSync(layoutsFolder)) {
  mkdirSync(layoutsFolder, {recursive: true});
  console.log(`Created layouts folder at "${layoutsFolder}"`);
}

// Check if the layout file already exists
const layoutFilePath = join(layoutsFolder, `${layoutName}.${componentExtension}`);

if (existsSync(layoutFilePath)) {
  console.error(`Layout "${layoutName}" already exists at "${layoutFilePath}".`);
  // eslint-disable-next-line no-undef
  process.exit(1);
}

// Create the new layout file
const layoutTemplate = `import React from 'react';

  const ${capitalizeFirstLetter(layoutName)} = () => {
    return (
        <div className={""}>
            <h1 className={""}>${capitalizeFirstLetter(layoutName)} Layout</h1>
        </div>
    );
};
  
export default ${capitalizeFirstLetter(layoutName)};
`;

writeFileSync(layoutFilePath, layoutTemplate);

console.log(`Layout "${layoutName}" created at "${layoutFilePath}"`);

// Check if the index file already exists
if (!existsSync(indexPath)) {
  writeFileSync(indexPath, `
  // This file is auto-generated by the create:layout script
  // Import and export your layouts here
  `);
  console.log(`Created index file at "${indexPath}"`);
}